print( rowland )
print( roselene )
print( bolajoko )
print( charles )
print(simeon )
print( rachael)
print( bisi )
print( adisa )
print( ray )
print( susan )
print( car services automated)
print( hello $user your car needs servicing )
